### ISSUE TITLE
Webdriverio v4.0.5 - synchronous

### ISSUE THREAD

**Issue by pi4r0n** [onewithhammer/web-driver-io-tutorial#1]
@onewithhammer  today I have been told that all commands in webdriverio v4.0.5 **are running synchronous**, which means done callbacks aren't defined. Do you think we need to update your tests ?

FYI
http://webdriver.io/guide/getstarted/v4.html

**Comment by onewithhammer** [comment]
Hi Arek - Yes. I need to update this project.  I was actively updating the project for about 6 months then I became busy with another project and haven't kept up with it.  I will update when I have some time.

**Comment by pi4r0n** [comment]
@onewithhammer  - Tony I have just clone the repo and will try to help you with this ;) unfortunately I dont have SAUCE account, but will test stuff local ;)

**Comment by jeznag** [comment]
@pi4r0n how'd you go with that? Happy to help out too.
